### ISSUE TITLE
Segfault / Coredump from github built image on x86_64

### ISSUE THREAD

**Issue by mikenye** [fredclausen/docker-acarshub#8]
Hi @fredclausen,

Just FYI, I've found that there's a problem with the x86_64 version of the image when built by GitHub.

`acarsdec` and `vdlm2dec` both segfault when started.

I think that this is due to compiler optimisations being too aggressive, and I'm experimenting with reducing them.

I've created the branch `troubleshoot_segfault` for the troubleshooting works.

-Mike

**Comment by mikenye** [comment]
Example errors:

`acarsdec`:
```
./run: line 56:  1013 Illegal instruction     (core dumped) "$ACARS_BIN" "${ACARS_CMD[@]}" 2>&1
```

`vdlm2dec`:
```
./run: line 54:  1192 Illegal instruction     (core dumped) "$VDLM_BIN" "${VDLM_CMD[@]}" 2>&1
```

**Comment by mikenye** [comment]
I think the culprits is this line in each util's CMakeLists.txt:

```cmake
add_compile_options(-Ofast -march=native )
```

According to `gcc` docs here: <https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html>:

> `-Ofast`:
> Disregard strict standards compliance. `-Ofast` enables all `-O3` optimizations. It also enables optimizations that are not valid for all standard-compliant programs. It turns on `-ffast-math`, `-fallow-store-data-races` and the Fortran-specific `-fstack-arrays`, unless `-fmax-stack-var-size` is specified, and `-fno-protect-parens`.

Also according to this post: <https://stackoverflow.com/questions/52653025/why-is-march-native-used-so-rarely>:

> Using `-march=native` is inappropriate for binaries that will be distributed to other machines.

...because...

> ... `-march=native`, which tells the compiler to tune generated code for the micro-architecture and ISA extensions of the host CPU.

So I will attempt the following:

- Reduce `-Ofast` to `-O2` (or lower); and
- Remove `-march=native`

This will hopefully make those binaries portable and fix the problem.

**Comment by fredclausen** [comment]
I've forked the acarsdec code and submitted a PR for the message truncation. Would it be worthwhile to just switch our container over to using that repository to pull acarsdec code? Would probably make changing the CMake changes easier.

I could fork vdlm2dec as well. The original author doesn't seem to commit often, or respond to issues/PRs on GH so we probably won't miss upstream changes if we do it this way.

**Comment by mikenye** [comment]
Just saw your reply.

> Would it be worthwhile to just switch our container over to using that forked repository to pull acarsdec code?

Yeah I think it would, at least until your PR gets accepted (if ever).

> I could fork vdlm2dec as well...

Agreed.

I'm currently running a test build with the optimisations disabled, and then I plan to increase them until it breaks, then roll back one.

If you're able to add me as a contributor to your forks, I'll update the CMakeLists.txt files once I find the appropriate settings and get the Dockerfile for this project updated.

Cheers mate.

**Comment by fredclausen** [comment]
I'll get that set up right now

**Comment by mikenye** [comment]
Seems that `-O2` is stable. Closing.
